name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

#    container:
#      image:  google/dart:latest

    steps:
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    # The flutter action needs java so include it
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    # Setup the flutter environment - include the flutter action
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', 'beta', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter

    # Get flutter dependencies.
    - name: Install dependencies
      run: flutter pub get

    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # Run widget tests for our flutter project.
    - name: Run tests
      run: flutter test

    # Build apk. (debug)
    - run: flutter build apk --debug
    # Upload generated apk to the artifacts. (debug)
    - uses: actions/upload-artifact@v1
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk

    # Build apk.
    - run: flutter build apk
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
